apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: pekerustallround
  namespace: peke-echo-v1
spec:
  deployment:
    istio:
      kind: Deployment
      labels:
        app: peke-echo-v1
        version: v1
  filter:
    config:
      '@type': type.googleapis.com/google.protobuf.StringValue 
      value: "{\"checksvc\":\"outbound|80||httpbin-v1.httpbin.svc.cluster.local\",\"headersEnabled\":true,\"bodyEnabled\":true,\"headers\":[\"*\"],\"body\":[\"$.\"],\"extraUrlsToMask\":\"quinten\"}"
    image: webassemblyhub.io/peke/pekerustallround:v0.1